# -*- coding: utf-8 -*-
"""多账号交替顶帖.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS3J6cCZfpOBFSEwR-rYy9Ud3ceRaJLs
"""

#coding:utf-8
import requests, time, random, urllib.parse, os
from lxml import html
from IPython.display import display, Image, clear_output
import ipywidgets as widgets
from hashlib import md5

# ================= 配置区 =================
ID = "这里输入帖子UID" #示例:https://movie.douban.com/review/17647190/ - 填写17647190
ACCOUNTS = [
    {'cookie': '这里账号A输入网页cookies', 'ck': '这里输入账号A四位CK编码'}, #教程详见README文档
    {'cookie': '这里账号B输入网页cookies', 'ck': '这里输入账号B四位CK编码'},
]
PARS = ["期待张泽禹在一路向海的少年里的精彩表现", "坐等开播！超级期待张泽禹的小舞台", "支持张泽禹的新节目", "一路向海的少年，张泽禹冲呀！"]

# ================= 核心逻辑 =================
def main_run(acc, idx):
    sess = requests.session()
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', 'Cookie': acc['cookie']}
    data = {'ck': acc['ck'], 'rv_comment': random.choice(PARS), 'submit_btn': '加上去'}

    try:
        resp = sess.post(f'https://movie.douban.com/subject/38500062/discussion/{ID}/add_comment', data=data, headers=headers)
        if "captcha_image" in resp.text:
            print(f"⚠️ [账号{idx}] 触发验证码")
        elif resp.status_code in [200, 302]:
            print(f"🎉 🎉 🎉 [账号{idx}] 发布成功 文案: {data['rv_comment']}")
        else:
            print(f"❌ [账号{idx}] 状态码: {resp.status_code} (建议此时点右上角断开运行)")
    except Exception as e:
        print(f"⚠️ 网络波动: {e}")

# 启动带倒计时的轮换系统
for i in range(200):
    main_run(ACCOUNTS[i % len(ACCOUNTS)], (i % len(ACCOUNTS)) + 1)

    # 倒计时模块 建议根据账号稳定程度将间隔时间设置在60-180秒之间 如需调试请先暂停运行
    wait_time = random.randint(60, 90)
    for remaining in range(wait_time, 0, -1):
        print(f"⏳ 正在休眠中，距离下一次发布还有 {remaining} 秒...", end='\r')
        time.sleep(1)
    print("\n" + "="*30)
