# -*- coding: utf-8 -*-
"""普通顶帖.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPnqQAWVz_ctjPKdumo7v8qqsoslpgKD
"""

#coding:utf-8

import requests
import time
import random
import re
import urllib.parse

def main():
    global sess
    sess = requests.session()
    print("程序开始")


    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Referer': f'https://www.douban.com/group/topic/{ID}',
        'Cookie': COOKIE,
        'Origin': 'https://www.douban.com',
        'Accept': 'application/json, text/javascript, */*; q=0.01',
        'Accept-Language': 'zh-CN,zh;q=0.9',
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'X-Requested-With': 'XMLHttpRequest',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin'
    }

    url_group = f'https://www.douban.com/group/topic/{ID}/add_comment'

    # 张泽禹应援词库 随意添加
    pars = [
        "超级期待张泽禹",
        "期待张泽禹在一路向海的少年的表现",
        "只期待张泽禹"
    ]
    one_par = pars[random.randint(0, len(pars)-1)]

    try:
        print(f"* 状态确认：正在使用安全凭证 {MY_CK} 发送应援内容... *")

        # 将表单数据进行手动的 URL 编码序列化，确保百分之百契合豆瓣底层接收格式
        form_data = {
            'ck': MY_CK,
            'rv_comment': one_par,
            'start': '0',
            'submit_btn': '发送'
        }
        encoded_data = urllib.parse.urlencode(form_data)

        # 发送请求
        html_group = sess.post(url_group, data=encoded_data, headers=headers)

        print(f">> 服务器原始回应状态码: {html_group.status_code}")

        # 豆瓣成功后通常会返回状态码 200（并在文本里包含跳转或者新发言 json）
        if html_group.status_code == 200:
            print(f"🎉 🎉 🎉 顶帖大成功！！成功发出: 【{one_par}】")
        else:
            print(f"❌ 发送失败，状态码: {html_group.status_code}")
            print(">> 提示：如果依然 403，请尝试在无痕浏览器中手动在该帖下发表任意一条评论，看账号本身是否被限制。")

    except Exception as e:
        print("## 运行期间发生未知错误 -", e, "##")

    finally:
        # 在这里可以控制总共运行的等待间隙
        pass

if __name__ == '__main__':
    raw_id = input("1. 请输入目标帖子链接或ID: ").strip()
    parsed_numbers = re.findall(r'(\d{7,12})', raw_id)
    ID = parsed_numbers[0] if parsed_numbers else raw_id

    COOKIE = input('2. 请粘贴你刚刚获取的完整 Cookie: ').strip()
    MY_CK = input('3. 请输入你当前账号真实的 4 位 ck 值 (如 9FZJ): ').strip()

    print('\n' + '='*50)
    print(f'* 准备为帖子 ID: {ID} 提供张泽禹顶帖应援')
    print('='*50 + '\n')

    # ===【数量调整核心区】===
    total_count = 100  # <--- 想要顶帖几次，就把这个数字改成几（比如 5、10、20）

    current_run = 0
    while current_run < total_count:
        current_run += 1
        print(f"\n🚀 开始执行第 {current_run} / {total_count} 次顶帖任务...")
        main()

        if current_run < total_count:
            # 每次顶帖成功/失败后的休息时间（单位：分钟）可根据自身账号稳定性修改
            delay_minutes = random.randint(10, 20)
            print(f"-> 本轮任务结束，安全进入冬眠，预计休息 {delay_minutes} 分钟...")
            time.sleep(60 * delay_minutes)

    print(f"\n🎉 目标达成！已成功执行完 {total_count} 次顶帖任务，程序安全退出。")